stages:
  - test

test:e2e:
  stage: test
  image: jaktestowac/python-chromedriver:3.6-xvfb

before_script:
    - python3 -V
    - python3 -m pip install pytest
    - python3 -m pip install selenium pytest
    - python3 -m pip install webdriver_manager
    - python3 -m pip install allure-pytest

      script:
    - export PYTHONUNBUFFERED=1
    - python3 -m pytest sample_tests.py
